[package]
name = "biff/duplicate-alias-different-realms"
version = "0.1.0"
license = "MIT"
realm = "server"
registry = "test-registries/primary-registry"

[dependencies]
Minimal = "biff/minimal-shared@0.1.0"

[server-dependencies]
Minimal = "biff/minimal@0.1.0"