steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/shiloh-wally-registry-bucket/wally-backend:$COMMIT_SHA', '-f', 'wally-registry-backend/Dockerfile', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/shiloh-wally-registry-bucket/wally-backend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "wally-backend",
        "--image",
        "gcr.io/shiloh-wally-registry-bucket/wally-backend:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--command",
        "./launch",
        "--allow-unauthenticated",
      ]

timeout: 900s
options:
 machineType: 'E2_HIGHCPU_8'
