version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: wally-registry-backend/Dockerfile
      args:
        - WALLY_BACKEND_BUILD_FEATURES=${WALLY_BACKEND_BUILD_FEATURES}
    ports:
      - "8000:8000"

  frontend:
    build: wally-registry-frontend
    ports:
      - "8001:8000"
    links:
      - backend
