[workspace]
members = ["modules/*"]
registry = "test-registries/primary-registry"

[workspace.place]
shared-packages = "game.ReplicatedStorage.Packages"
server-packages = "game.ServerScriptService.Packages"
