[package]
name = "biff/dev-dependency"
version = "0.1.0"
license = "MIT"
realm = "server"
registry = "test-registries/primary-registry"

[place]
server-packages = "game.ServerScriptStorage.Packages"

[dev-dependencies]
Transitive = "biff/transitive-dependency@0.1.0"
