name: CI

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Install Rust
      uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      with:
        components: rustfmt, clippy

    - name: Build
      run: |
        sudo apt-get install libssl-dev
        cargo build --verbose --locked

    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy

    - name: Test
      run: cargo test --verbose --locked
