name: CI

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust_version: [stable]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust toolchain
      run: rustup default ${{ matrix.rust_version }}

    - name: Build
      run: cargo build --all --verbose --locked
      env:
        OPENSSL_STATIC: 1

    - name: Run tests
      run: cargo test --all --verbose --locked

    - name: Rustfmt and Clippy
      run: |
        cargo fmt --all -- --check
        cargo clippy --all
      if: matrix.rust_version == 'stable'
