name: Release

on:
  push:
    tags: ["*"]

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  build-release:
    name: Build release
    id: build
    uses: ./.github/workflows/build.yml
    needs: ["create-release"]
    with:
      release_ref: ${{ github.ref_name }}

  - name: Upload wind64 build
    uses: actions/upload-release-asset@v1
    needs: ["build"]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}
      asset_path: wally-${{github.ref_name}}-win64.zip
      asset_name: wally-${{github.ref_name}}-win64.zip
      asset_content_type: application/octet-stream

  - name: Upload macos build
    uses: actions/upload-release-asset@v1
    needs: ["build"]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}
      asset_path: wally-${{github.ref_name}}-macos.zip
      asset_name: wally-${{github.ref_name}}-macos.zip
      asset_content_type: application/octet-stream

  - name: Upload linux build
    uses: actions/upload-release-asset@v1
    needs: ["build"]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}
      asset_path: wally-${{github.ref_name}}-linux.zip
      asset_name: wally-${{github.ref_name}}-linux.zip
      asset_content_type: application/octet-stream