name: Tree

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust_version: [stable]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust toolchain
      run: rustup default ${{ matrix.rust_version }}

    - name: Build
      run: cargo tree
      
    - name: Build
      run: cargo tree -i openssl-sys

    - name: Build
      run: cargo build --all --verbose --locked

    - name: Run tests
      run: cargo test --all --verbose --locked

    - name: Rustfmt and Clippy
      run: |
        cargo fmt --all -- --check
        cargo clippy --all
      if: matrix.rust_version == 'stable'